# Generated by Django 4.1.4 on 2022-12-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IjtimoiyTarmoqLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=244, verbose_name='Telegram Havolasi')),
                ('instagram', models.CharField(max_length=244, verbose_name='Instagram Havolasi')),
                ('youtube', models.CharField(max_length=244, verbose_name='Youtube Havolasi')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq havolasi',
                'verbose_name_plural': 'Ijtimoiy tarmoq havolarali',
            },
        ),
    ]
